create extension if not exists pgcrypto;
create table if not exists public.trips(id uuid primary key default gen_random_uuid(),name text not null,destination text not null,start date,"end" date,budget numeric not null default 0,share_code text unique not null,created_by uuid not null,created_at timestamptz not null default now());
create table if not exists public.trip_members(trip_id uuid references public.trips(id) on delete cascade,user_id uuid,display_name text,created_at timestamptz default now(),primary key(trip_id,user_id));
create table if not exists public.flights(id uuid primary key default gen_random_uuid(),trip_id uuid references public.trips(id) on delete cascade,airline text,number text,from_airport text,to_airport text,date date,time text,terminal text,booking_ref text,price numeric default 0,created_at timestamptz default now());
create table if not exists public.stays(id uuid primary key default gen_random_uuid(),trip_id uuid references public.trips(id) on delete cascade,name text,start date,"end" date,address text,phone text,booking_ref text,price numeric default 0,created_at timestamptz default now());
create table if not exists public.plans(id uuid primary key default gen_random_uuid(),trip_id uuid references public.trips(id) on delete cascade,title text,date date,time text,place text,notes text,created_at timestamptz default now());
create table if not exists public.expenses(id uuid primary key default gen_random_uuid(),trip_id uuid references public.trips(id) on delete cascade,label text,category text,amount numeric default 0,payer text check(payer in('Alexis','Alix')),created_at timestamptz default now());
create table if not exists public.documents(id uuid primary key default gen_random_uuid(),trip_id uuid references public.trips(id) on delete cascade,name text,doc_type text,url text,storage_path text,created_at timestamptz default now());
create or replace function public.is_member(t uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.trip_members where trip_id=t and user_id=auth.uid())$$;
create or replace function public.create_trip(p_name text,p_destination text,p_start date,p_end date,p_budget numeric,p_alexis_name text default 'Alexis') returns table(trip_id uuid,share_code text) language plpgsql security definer set search_path=public as $$declare i uuid;c text;begin c=upper('NV-'||substr(encode(gen_random_bytes(5),'hex'),1,7));insert into public.trips(name,destination,start,"end",budget,share_code,created_by) values(p_name,p_destination,p_start,p_end,p_budget,c,auth.uid()) returning id into i;insert into public.trip_members values(i,auth.uid(),p_alexis_name,now());return query select i,c;end$$;
create or replace function public.join_trip(p_share_code text) returns table(trip_id uuid,share_code text) language plpgsql security definer set search_path=public as $$declare i uuid;c text:=upper(trim(p_share_code));begin select id into i from public.trips where trips.share_code=c;if i is null then raise exception 'Code de voyage introuvable';end if;insert into public.trip_members values(i,auth.uid(),'Alix',now()) on conflict do nothing;return query select i,c;end$$;
grant execute on function public.create_trip(text,text,date,date,numeric,text) to anon,authenticated;grant execute on function public.join_trip(text) to anon,authenticated;grant execute on function public.is_member(uuid) to anon,authenticated;

alter table public.trips enable row level security;alter table public.trip_members enable row level security;alter table public.flights enable row level security;alter table public.stays enable row level security;alter table public.plans enable row level security;alter table public.expenses enable row level security;alter table public.documents enable row level security;
create policy trips_s on public.trips for select using(public.is_member(id));create policy trips_u on public.trips for update using(public.is_member(id));create policy members_s on public.trip_members for select using(public.is_member(trip_id));create policy flights_a on public.flights for all using(public.is_member(trip_id)) with check(public.is_member(trip_id));create policy stays_a on public.stays for all using(public.is_member(trip_id)) with check(public.is_member(trip_id));create policy plans_a on public.plans for all using(public.is_member(trip_id)) with check(public.is_member(trip_id));create policy expenses_a on public.expenses for all using(public.is_member(trip_id)) with check(public.is_member(trip_id));create policy docs_a on public.documents for all using(public.is_member(trip_id)) with check(public.is_member(trip_id));
